// examples/vue3/src/components/content.vue
<template>
  <div>
    <div>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam aliquid
        perferendis, adipisci dolorum officia odio natus facere cumque iusto libero
        repellendus praesentium ipsa cupiditate iure autem eos repudiandae delectus
        totam?
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo praesentium,
        aperiam numquam voluptatibus asperiores odio? Doloribus saepe, eligendi facere
        inventore culpa, exercitationem explicabo earum laborum deleniti reiciendis
        deserunt accusantium ullam.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia voluptas
        numquam impedit architecto facilis aliquam at assumenda, nostrum explicabo
        accusantium ipsam error provident voluptate molestias magnam quisquam
        excepturi illum sit!
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, accusantium
        quo corporis fugit possimus quaerat ad consequatur veniam voluptatum ut cumque
        illo beatae. Magni assumenda eligendi itaque eum voluptate non!
      </p>
    </div>
    <img
      src="https://gw.alipayobjects.com/zos/bmw-prod/d283f09a-64d6-4d59-bfc7-37b49ea0da2b.svg"
      alt="示例图片"
      :width="600"
      :style="{ zIndex: 10, maxWidth: '100%', position: 'relative' }"
    />
  </div>
</template>

// docs/components/content/index.tsx
export default () => {
  return (
    <>
      <div>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam aliquid
          perferendis, adipisci dolorum officia odio natus facere cumque iusto libero
          repellendus praesentium ipsa cupiditate iure autem eos repudiandae delectus
          totam?
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo praesentium,
          aperiam numquam voluptatibus asperiores odio? Doloribus saepe, eligendi facere
          inventore culpa, exercitationem explicabo earum laborum deleniti reiciendis
          deserunt accusantium ullam.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia voluptas
          numquam impedit architecto facilis aliquam at assumenda, nostrum explicabo
          accusantium ipsam error provident voluptate molestias magnam quisquam
          excepturi illum sit!
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, accusantium
          quo corporis fugit possimus quaerat ad consequatur veniam voluptatum ut cumque
          illo beatae. Magni assumenda eligendi itaque eum voluptate non!
        </p>
      </div>
      <img
        src="https://gw.alipayobjects.com/zos/bmw-prod/d283f09a-64d6-4d59-bfc7-37b49ea0da2b.svg"
        alt="示例图片"
        width={600}
        style={{ zIndex: 10, maxWidth: '100%', position: 'relative' }}
      />
    </>
  )
}
